pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f Jenkins_Upgradev3/java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy in Staging Environment'){
            steps{
                echo "Now Archiving the Artifacts...."
 
            }
            
        }
        stage('Deploy to Production'){
            steps{
                timeout(time:5, unit:'DAYS'){
                    input message:'Approve PRODUCTION Deployment?'
                }
                echo "Now Archiving the Artifacts...."
            }
        }
    }
}
